### ISSUE TITLE
logger not added correctly

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#101]
https://github.com/databio/logmuse/issues/4#issuecomment-481724999

**Comment by nsheff** [comment]
running caravel says:

```No handlers could be found for logger "looper.project"in any repository but it should also be downgraded.
```

@vreuter : 
> It's emitted from logging itself when a call is made on a logger with no handlers.

**Comment by nsheff** [comment]
did we ever figure this out?

**Comment by michalstolarczyk** [comment]
This message is not showing for me. We might've solved it along the way
