### ISSUE TITLE
lump and lumpn defaults

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#108]
the caravel defaults for lump and lumpn appear to be the maximum; they don't match the defaults for looper (which are off)

**Comment by michalstolarczyk** [comment]
As discussed with @nsheff, the options that are off (`None`) by default will be inactive sliders/checkboxes in the future version. 

The workaround for the problem raised here is to set (just in `caravel`) the defaults of `lumpn` and `lump` to 1 and 0, respectively. These values should mimic the `looper` "off" behavior for now.
