### ISSUE TITLE
summarizing a project that has not been run leads to an error

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#111]
Caravel server encountered exception(s):

    UnboundLocalError: local variable 'stats_file_path' referenced before assignment

We should instead just say something about not being able to summarize.

**Comment by michalstolarczyk** [comment]
Can't reproduce this, this worked for me:

1. remove the whole `output_dir`
1. start `caravel`
1. go to "Process"
1. summarize

No errors, the summary pages just do not show any samples, objects etc

Can you provide more background to that situation?
