### ISSUE TITLE
update all the displayed project object attrs in the process page

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#113]
if you specify a `subproject` that alters the `metadata.output_dir`, activating  `subproject` still uses the primary `output_dir` and does not respect the modification expected by the subproject.

**Comment by michalstolarczyk** [comment]
All the project attributes are updated correctly, since `activate_subproject` method is used to do so. The updated information is just not displayed in `caravel`.

Will need to work on updating what's displayed as well..
