### ISSUE TITLE
link to compute settings on main page

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#114]
Raised by @rcorces

the gear icon is not immediately recognizable as computing options. This could be explained with a link on the primary page, where projects are selected, to guide new users.

**Comment by rcorces** [comment]
ah. yes. the gear is what i was looking for. I originally was looking down in the "Set options" section. I'm not sure who has been working on caravel but it is REALLY nicely done. I'm very impressed.

**Comment by michalstolarczyk** [comment]
Thanks for your feedback, @rcorces!

**Comment by michalstolarczyk** [comment]
I added a button with text and the gear icon to the index page, let's hope users will associate the gear icon with computing environment configuration afterwards 🤞
