### ISSUE TITLE
Improving the user interface

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#126]
I'd like to take some concepts we developed in refgenie and apply them to caravel.

~~1. The 'caravel config' file (which is just a list of projects) can be analogous to `refgenieserver`' genome config file. caravel could read, **write**, and manage this file. Instead of just a dropdown to select a project from this list, caravel instead displays a list of projects, which are links, where clicking on the project brings you to the project splash page. This list would have a few other metadata about the project, such as number of samples, number of subprojects, total size of inputs, total size of outputs (maybe? we'd need to calculate these smartly), date last modified, and probably a load of other metadata eventually. this is more convenient and informative than the current dropdown~~. Done

Caravel can have an 'add project' button that would add an entry to this page, probably even using peppy to create a skeleton PEP, in a configurable folder structure of interest 

we should move forward with #79, creating a new tab for geofetch. this would interface with the point above because it's one way create a new project. in fact, maybe this *is* the 'add project' button...with `geofetch` being one option in this interface.

**Comment by michalstolarczyk** [comment]
Ok, this seems like a lot of improvements/changes again. Should we release the recent improvements before I start working on this? Most importantly, this release would include the demo

**Comment by nsheff** [comment]
Yes. release current one first.

**Comment by michalstolarczyk** [comment]
a few changes: 
- [ ] remove Subprojects count column
- [ ] move the Action column to the left 
- [ ] include a GO/RUN button in the Action column
- [ ] the projects and subprojects names are not buttons, just text. The action of current buttons will be performed on GO/RUN click
- [ ] make the subprojects expand and collapse on `>` click next to the project
- [ ] move the name of the expanded subprojects to the Project name column
