### ISSUE TITLE
caravel should be installable and have a command-line interface

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#13]
RIght now we have to run caraval by calling `FLASK_APP=blah flask run blahblahblah`.

It would be nicer if we could wrap all this into something so we can just say `caravel` and it will run (like we did with `looper`).

then it should also be able to take a  few parameters... one being the config file (see #12)

**Comment by vreuter** [comment]
Yep

**Comment by nsheff** [comment]
This appears to have reverted in the current dev branch

**Comment by nsheff** [comment]
Just kidding.
