### ISSUE TITLE
Using divvy

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#53]
Caravel should make use of the new divvy functionality to configure the computing environment, and allow a select box for compute package.

there should be a 'settings' link in the nav. this should let you select your compute package. maybe it displays the current compute package, all its options, etc.

currently, it's just letrting looper -> peppy do this, but we should instead control computing configuration at the caravel environment stage, rather than at the project stage, so caravel should use divvy directly instead of using that functionality as part of peppy.

**Comment by nsheff** [comment]
is caravel using divvy now?

**Comment by michalstolarczyk** [comment]
Yes, in the `set_comp_env` route
