### ISSUE TITLE
exclude/include protocols in caravel?

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/caravel#59]
Do we add the `--exclude-protocols`/`--include-protocols` option to `caravel` or work on  https://github.com/pepkit/peppy/issues/245 and use more generic sample exclusion mechanism in `looper` and `caravel`?

Ultimately we will need a more sophisticated sample selection mechanism anyway as in future versions of `caravel` we aim to implement an interactive sample selection from within the web UI (see: #58).

**Comment by vreuter** [comment]
I think it makes sense to proceed with the more powerful, general solution in `peppy` and then use that here, but I'm open.

**Comment by michalstolarczyk** [comment]
That's what I did. Closing
