### ISSUE TITLE
show python version

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#64]
should we have caravel show python version it's using? at least on the command line...I'd also do it on the tagline in the HTML.

**Comment by michalstolarczyk** [comment]
> should we have caravel show python version it's using? at least on the command line
Yeah, good idea.

> I'd also do it on the tagline in the HTML.
What do you mean by tagline? Navbar?

**Comment by nsheff** [comment]
not navbar, just the line where it already has the caravel/looper versions
