### ISSUE TITLE
summarize subprojects

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#65]
I'm not 100% sure but in a brief test, it appeared that calling `summarize` from caravel does NOT summarize the active subproject, but the main project instead;

furthremore, the get summary is not getting the subproject summary, but the main summary.

summarize, like run, should use the subproject to pass that parameter on; also the get summary will need to tweak the file name to grab the subjproject summary file, which differs from the main one.

**Comment by michalstolarczyk** [comment]
Probably related to: https://github.com/pepkit/looper/issues/112

**Comment by nsheff** [comment]
summarizing is working now, but "See summary" still goes to the parent (not active subproject) summary).

**Comment by michalstolarczyk** [comment]
should be fixed now

**Comment by nsheff** [comment]
sort of; it requires a refresh to update the see summary link...

**Comment by michalstolarczyk** [comment]
the link is changed at the page load. Are you suggesting it should be also changed at the subproject activation/deactivation?

**Comment by nsheff** [comment]
shouldn't it? I activate a subproject, and then click summary, it shows the primary one? No, it shows the subproject summary of course.
