### ISSUE TITLE
reseting doesn't change the subproject badge text

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#73]
if I click 'start over' and then initialize a different project, it still says "active subproject: blah" from the previous project (the current project doesn't even have that subproject).

**Comment by michalstolarczyk** [comment]
I encountered that before and that's what https://github.com/pepkit/caravel/issues/70 was about. 

Do you run the latest `dev` version?

**Comment by nsheff** [comment]
yeah I think so, but I'll double-check I guess.

**Comment by michalstolarczyk** [comment]
@nsheff this should get fixed after 5172dbe. Closing
