### ISSUE TITLE
Project order

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#74]
projects are not listed in the same order they are in the yaml file.

**Comment by michalstolarczyk** [comment]
I went with alphabetical order: #46. Do you feel strongly about preserving the one in the config?

**Comment by nsheff** [comment]
I guess I think probably we will ultimately change this interface around anyway... for example, maybe it should show the actual project name, or something. Though, that requires reading in the project, I suppose... that wouldn't be good.

I think preserving the order makes most sense to me but I don't feel strongly at the moment.
