### ISSUE TITLE
link to process

### ISSUE THREAD

**Issue by nsheff** [pepkit/caravel#77]
there should be a link  to `process` in the nav so you can go back and forth from environment to process without having to re-load a project.

if there is no active project it could say so.

**Comment by michalstolarczyk** [comment]
> if there is no active project it could say so.

I decided to just redirect to the index (to select the project) if the process link if the navbar is clicked with no activated project.

**Comment by michalstolarczyk** [comment]
Also, I didn't know which favicon to choose, feel free to change/suggest it if you find sth that fits better!

**Comment by nsheff** [comment]
I like the new link to process -- but it doesn't work... when I click it, even after a project is loaded, it says "no project loaded"

**Comment by nsheff** [comment]
just realized: it works in chrome but not firefox. that's quite strange.

**Comment by michalstolarczyk** [comment]
I works perfectly fine for me, do you get any errors/warnings on the terminal?

**Comment by michalstolarczyk** [comment]
> just realized: it works in chrome but not firefox. that's quite strange

Oh, that's weird indeed. Works in safari

**Comment by michalstolarczyk** [comment]
... and Firefox for me on mac

**Comment by michalstolarczyk** [comment]
Can't reproduce it on Firefox on Linux as well

**Comment by nsheff** [comment]
Ok strange it's soft of working for me now... maybe the update fixed this, but there's a related issue... Steps to reproduce:

load caravel
load a project by pressing "go"
click "Home"
click "Process"

Shouldn't this retain the already-loaded project?

**Comment by michalstolarczyk** [comment]
I see. I'm removing the project data intentionally there, since choosing a project is the only functionality of the "Home" tab, so there's no reason to preserve the loaded project. 

On second thought, having the "Start over" button is misleading for user that doesn't know the above. So I think I agree with preserving the selected project

**Comment by nsheff** [comment]
I think old project should not ever be removed until a new project is loaded.

**Comment by michalstolarczyk** [comment]
Agreed, but with the exception of clicking "Start over", which explicitly states that the data will not be preserved.
