### ISSUE TITLE
looper options form layout 

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/caravel#81]
move the form elements labels to the left, group by element type, work on spacing

**Comment by nsheff** [comment]
here are the two changes to make that will bring the form much tighter.

class `col-form-label`:
padding (top and bottom) -> currently set to: 7, change to: 0

so anything set to that class needs to reduce padding

you're using the `<pre>` tag for the option names, which has margin-bottom currently set: 1rem; change to: 0.

**Comment by nsheff** [comment]
that's great --

next; there's a problem with small-window collapsing... watch as you shrink your window size. you are moving items over way before necessary. specifically, the slider *numbers* move way too early. also there is too much space between those numbers and the text label.
