### ISSUE TITLE
Use looper HTML reports to produce the summary

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/caravel#84]
`caravel` could use HTML reports part of `looper` and create the summary pages on its own, not by running `looper summarize`. 

This depends on https://github.com/pepkit/looper/issues/127

**Comment by michalstolarczyk** [comment]
I'm done with the `looper` reporting integration for a few days now and I've been correcting some minor stylistic problems since then. 

@nsheff once you get a chance, can you test  `caravel` on `dev`  using `looper` on `jinja` with your 200+ samples project? If this works, it's safe to close this and proceed with the release

**Comment by nsheff** [comment]
let's go ahead do the jinja -> dev merge now and then I'll give a test run before the dev -> master release.
