### ISSUE TITLE
os.getlogin

### ISSUE THREAD

**Issue by vreuter** [pepkit/caravel#96]
The `os.getlogin` call can hit exception, `OSError` in python2 and `FileNotFoundError` in python3.5. Ubuntu 16.04 + python 3.5.2 and python 2.7.12. https://github.com/pepkit/caravel/blob/dev/caravel/caravel.py#L465

**Comment by vreuter** [comment]
Can we take the suggestion from the PSF docs? https://docs.python.org/3/library/os.html#os.getlogin

**Comment by michalstolarczyk** [comment]
yes, that's exactly what I've started doing
